---
- hosts: vhpa_servers
  tasks:
    - dnf: name=centos-release-stream state=latest
    - shell: dnf swap -y centos-{linux,stream}-repos
    - shell: dnf -y distro-sync
    - reboot:
    - user: name=root password={{ root_password | password_hash('sha512') }}
